Glamorous implementation
hexacta/sanata pull request #31
Opened 2017-07-04 15:02 UTC by anicarrr

Here it goes!

2017-07-05 12:49 UTC, pomber commented
Awesome!

2017-07-05 12:52 UTC, pomber requested changes

2017-07-05 12:52 UTC, pomber commented on web/package.json
> +    "glamorous": "^3.23.2",
Shouldn't these be `dependencies` instead of `devDependencies`?

2017-07-05 12:52 UTC, pomber commented on web/src/Form.js
> +      >
I would add `const {height, width, radius, alpha, loading} = this.props;` to avoid using `this.props` every time.

2017-07-05 14:31 UTC, anicarrr commented on web/src/Form.js
> +      >
I was about to do that!

Something that makes noise for me is the fact of transfering props for styling and bussines logic in the same component. Maybe the Getter approach for styling was more cleaner.

2017-07-05 14:41 UTC, pomber commented on web/src/Form.js
> +      >
I agree, looks better with the `get formStyle()`

2017-07-05 14:48 UTC, anicarrr commented on web/src/Form.js
> +      >
Maybe we can use glamorous for static styling and for the dynamic ones use Getters.

2017-07-07 14:48 UTC, pomber commented
Add back the getters for dynamic styles and fix the dependencies in package.json and I'll merge this PR. We can continue with the rest of the files with another PR. Thanks!

2017-07-14 16:00 UTC, anicarrr commented
Now it's a good for merging ;)

I'll will continue with the rest on another PR.

2017-07-19 14:47 UTC, pomber approved these changes

2017-07-19 14:48 UTC, pomber commented
Niiiice

2017-07-19 14:48 UTC, merged